Vagrant::Config.run do |config|

  config.vm.box = "ubuntu-precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = "manifests"
     puppet.manifest_file  = "base-hadoop.pp"
     puppet.module_path = "modules"
  end

  config.vm.define :master do |master|
    master.vm.network :hostonly, "192.168.1.10"
    master.vm.host_name = "master"
  end
end
